### ISSUE TITLE
"NULL" HPO IDs in API

### ISSUE THREAD

**Issue by amwenger** [ajratner/dd-genomics#132]
The [DeepDive Genomics API](http://raiders2:8093/) shows HPO IDs of NULL for many results.  Try searching with geneId="%IFIH1" and minMaxExpC="0.5":

![null_hpoid](https://cloud.githubusercontent.com/assets/7155109/9392606/913e8748-4732-11e5-8785-bec827410aa7.png)

**Comment by Colossus** [comment]
I fixed this by selecting only gene-pheno pairs where both gene and pheno entities are not null into the genepheno_pairs table. I hope this is the right fix de jure. Currently running on genomics_production; will close if everything goes as planned.

**Comment by amwenger** [comment]
@Colossus That fix sounds like it will eliminate any NULLs, but are you sure that it's not just masking an deeper problem?  In the example screenshot, we should have extracted "rheumatoid arthritis" and "diabetes" as phenotypes paired with the gene IFIH1.  Are those truly extracted and IFIH1-NULL is just a negative training example, or should IFIH1-NULL actually be IFIH1-diabetes?

**Comment by Colossus** [comment]
@amwenger The genepheno supervision is currently set up such that it will take only the closest genepheno hit available. In the current situation, if a negative supervision phenotype (with entity NULL) is inserted into the pheno_mentions table BETWEEN a gene and the actual phenotype, the NULL value is erroneously converted to a string and DeepDive thinks the thing is an actual phenotype --- at least that's my diagnosis. But thanks for the heads up --- I'll definitely check if this problem is fixed (i.e. at least one of the phenotypes you mentioned is linked to the gene in your sentence) after this DD run.

**Comment by ajratner** [comment]
Resolved

**Comment by ajratner** [comment]
Note: the surface issue ("NULL" as a string) is resolved, the bigger issue is just re-calibrating everything (see #133, #134)
