### ISSUE TITLE
Fix make_all- referencing a file in robinjia's directory which no longer exists...

### ISSUE THREAD

**Issue by ajratner** [ajratner/dd-genomics#135]
@SenWu

**Comment by senwu** [comment]
After run ./make_all.sh, I got 
 Copying meshToPmid.tsv from local filesystem failed.
 If have access to raiders2, run scp username@raiders2:/lfs/raiders2/0/robinjia/data/meshToPmid.tsv data/meshToPmid.tsv
 Otherwise, use ./makeMeshToPmid.sh to re-generate file by querying PubMed.
 Then, re-run this script.

No such file or directory in raiders2:/lfs/raiders2/0/robinjia/data/meshToPmid.tsv data/meshToPmid.tsv

**Comment by Colossus** [comment]
Sorry Sen! This directory doesn't exist anymore. Please use:
/lfs/raiders2/0/jbirgmei/dd-genomics/onto/data/meshToPmid.tsv . I hope
this works, I can also copy it somewhere else in case not.

**Comment by Colossus** [comment]
Sorry Sen! This directory doesn't exist anymore. Please use
/lfs/raiders2/0/jbirgmei/dd-genomics/onto/data/meshToPmid.tsv . If it's
not accessible, I'm happy to copy this somewhere else.

**Comment by senwu** [comment]
Yes, I know it doesn't exist anymore. Could you fix the script?

**Comment by Colossus** [comment]
ok, pull
