### ISSUE TITLE
Finish moving raw PMC data -> dfs

### ISSUE THREAD

**Issue by ajratner** [ajratner/dd-genomics#21]

**Comment by ajratner** [comment]
In progress... [dfs very slow].  For now see `/dfs/scratch0/ajratner/dd_raw_docs` for PLoS subset, or `raiders4:/lfs/local/0/czhang/pmc_raw` (where the data is being copied from)

**Comment by ajratner** [comment]
Copying now.  `dfs` is really slow, might take a few days, clearly we don't want to process from here but this will just be where archived backup of all raw data goes

**Comment by amwenger** [comment]
`raiders4:/lfs/local/0/czhang/pmc_raw` has 1,051,887 files (155,754 copied as of 2015-07-15 10:15am).  It does take a long time to just allocate that many files.  Big directories like "PLoS_One", which has 124,602 files, can also be quite slow.  If it's just a backup, perhaps you should tar the files on `lfs` and then copy to `dfs`.

Take a look at rsync instead of cp.  It is more robust, gives you progress, and allow partial restarts:

```
rsync -aPv /lfs/local/0/czhang/pmc_raw/  /dfs/scratch0/ajratner/dd_raw_docs
```

**Comment by ajratner** [comment]
@amwenger Thanks!

**Comment by netj** [comment]
When creating the giant tarball backup, you can of course directly create it on dfs, skipping the last copying step:

``` bash
tar vzcf /dfs/scratch0/ajratner/dd_raw_docs.tar.gz -C /lfs/local/0/czhang/pmc_raw/ .
```

If mirroring the directory hierarchy is the goal, rsync is almost always the best, but if it ever feels too heavy, you could combine two `tar`s to preserve everything exactly:

``` bash
tar cf - -C /lfs/local/0/czhang/pmc_raw/ . | tar vxf - -C /dfs/scratch0/ajratner/dd_raw_docs
```

Note that this works over ssh as well.

**Comment by ajratner** [comment]
Wow do I love issues- this is awesome.  thanks guys!  I think rsync is good choice here, Aaron is right that the sheer number of files rather than uncompressed volume is the difficulty here... anyway copying now
