### ISSUE TITLE
Dashboard corpus-stats A priori dataset sizes: currently gene=gene names (not gene objects)

### ISSUE THREAD

**Issue by gbgbg** [ajratner/dd-genomics#219]
Snapshot 20151015-4

From the report:

```
A priori dataset sizes

11,326 HPO phenotypic abnormalities

107,239 Genes
    19,123 Canonical
    31,682 Noncanonical
    19,796 Ensembl IDs
    37,034 RefSeq IDs

419,854 Charité supervised genepheno relationships (canonicalized) 
```

Your number of genes is the sum of the four categories below it.
It's really the number of gene names we look for.
Replace with the number of unique gene entities (the platonic objects)
I don't know if that's equal to the number of ensembl ID or some union.
Will know after the swap.

**Comment by gbgbg** [comment]
Aside: we have only protein coding names there or also some ncRNAs? I do not remember.

**Comment by gbgbg** [comment]
```
 Number of distinct gene candidates
17,656 unique gene candidates (true/null)
...
```

So there are platonic gene objects
different gene names
and different gene name mentions...

this gets unwieldy fast.
i dont want to ask for more numbers
but maybe clarify which object is discussed at all times.
here i'm unsure if its platonic objects or gene names 
i suspect its gene names

FWIW i think the interesting quantities are
- gene objects
- gene names per category (canonocial, non, ensembl, refseq)
  the latter may be tedious to produce and its real goal is to make sure synonyms from all four categories are being used.

The former is more interesting science wise.
Maybe its there and I dont get it.

**Comment by Colossus** [comment]
OK, I see we need to discuss all this soonish, because I'm having some trouble extracting what you are confused about from up there.

A little tutorial first maybe.

The gene names input file was stolen from Ensembl. Whatever is in there is in our input file.

Ensembl genes have exactly one ENSG identifier. Most (except for the notorious 608) also have exactly one canonical name. In addition, many of these genes have a number of noncanonical names.

That's the essence. We can discuss the rest tomorrow.

It's good to know that some of these genes have suspiciously many synonyms, and I already knew that 608 ENS-genes didn't have a canonical name, but these issues are only marginally important. 

This is immediately evident from the numbers in gene-candidates, genepheno-candidates and inference etc. There's just no-one who mentions these wild synonyms for TP53, so I actually don't care if they're in our gene set. If they were giving us trouble, I'd cut them out. 

Until we're having trouble with them, I'm wouldn't like to clean this gene names file manually, because 
- it is huge. I'm not sure if I want to spend a few weeks finding out which synonyms in a 100,000 line file are important and which are not
- only tiny parts of it COULD give us trouble (but are not actually giving us trouble, apparently)
- and Ensembl is enough of a trustworthy source that I feel we don't really have to clean up after them.

We're certainly not doing any shuffles with this file. This is Ensembl, verbatim, period.

**Comment by gbgbg** [comment]
Okay so there are exactly  19,796 Ensembl IDs / gene _objects_. Got it.
So, for me the 107,239 are gene _names_, not "genes".
You can change the labels to help me out or I can hope to get used to it and NOT ask same again in N months. 

(And I dont care about P53 synonyms either - I'm picking on outliers in case they raise a suspicion with you for a more systemic issue. Otherwise ignore them. I agree we're not out to scrub singletons)

**Comment by Colossus** [comment]
OK, I'll clean it up. Maybe we can go over the whole thing tomorrow and I'll write down what's unclear.

**Comment by gbgbg** [comment]
might be better
i'll keep rummaging and making notes to myself for tomorrow - feel free 
to ignore
do get on meet gill
-g

**Comment by gbgbg** [comment]
Not to open a pandora box, do HPO phenotypes not also come with (some) synonyms?
So, when you say pheno... you mean what I call pheno objects or pheno names?

**Comment by Colossus** [comment]
HPOs do come with synonyms, but these are completely hidden in Dashboard. Dashboard only talks about HPO IDs.
