### ISSUE TITLE
Some sort of memory error w pheno_extract_candidates

### ISSUE THREAD

**Issue by ajratner** [ajratner/dd-genomics#42]
Seems like it occurs when loading the pmid to mesh mapping but this doesn't make sense... need to figure this out.  Also in general reducing the memory overhead for pheno would be good thing to do

**Comment by ajratner** [comment]
Loading the mesh-supervised hpo-pmid mappings seems to be both incredibly slow and memory-inefficient (a 3.5GB data structure in python from a 300MB file!).  However I'm still confused as to why this is happening now, and would like to clear this up, in addition to making this way less memory inefficient.  @Colossus any ideas of recent changes that could have caused this?

Again we're not hitting the machine's memory limit only the 256g we allocate in env_local I believe...

**Comment by Colossus** [comment]
A few interesting facts about the giant ontodata/hpo_to_pmid_via_mesh.tsv:
- Contains only 1026 unique hpo IDs
- Contains 8126995 (!) unique pubmed IDs. (Really?)
- Any obvious mistakes such as duplicate lines did not happen.

OK. Now perhaps we better ask ourselves how useful the original file meshToPmid.tsv is. [... deleted part for stupidity.]

However, there are 8 million (!) pubmed IDs in there. [... again deleted part of previous comment for stupidity.] There's this MeSH search engine on NCBI which is apparently nothing different than a text search engine with a restricted set of text search terms, among them a few HPO terms. However, they're probably not performing anything more sophisticated for detecting phenotypes than we are. (Rather the other way round.) **Which makes me question the usefulness of this particular distant supervision data source.**

**Comment by Colossus** [comment]
I had a good look at this error and I'm not at all sure what caused it to happen all of a sudden, but for some reason this defaultdict thing just consumes a few gigabytes of RAM, which times 80 leaves us fills the RAM pretty quickly. 

I think we might not have anything to do with it: It's just that for some reason more than half of the terabyte of RAM on raiders2 is permanently taken by some processes for some reason. (User `caberger` in particular is permanently running (eyeballing) around 50-100 processes, each consuming 0.4% of RAM, which processes miraculously hardly take any CPU, but are very efficient at filling memory.) 

This might not have been the case a few days ago, and then the data structure might just have fit. Now with only half of the RAM there, we'll just crash.

**Comment by ajratner** [comment]
@Colossus I'll take a look at their description of where this comes from at some pt but seems like we should scrap it.  The only relevance anyway is catching a few non-exact-match pheno candidates and supervising them as true (and if this set was machine generated, they probably just did the same thing...)

In terms of memory: I have to look into to be sure but the limit we're hitting is the `256g` defined in `env.sh` (~3.5GB x 80 processes = 280GB...).  Chris A.'s processes are zombie, I asked him, meaning we might need to restart raiders2 at some pt.  However they seem to be only consuming 0.4% = 40GB of RAM total (e.g. run `htop`).

So I am still really stumped as to why this is happening now all of a sudden... **However regardless we should reduce the pheno_candidate_extractor memory overhead- so seems like you could just scrap the MeSH supervision entirely for now, so that you can run everything?**

**Comment by Colossus** [comment]
Yeah, I'll do that.

**Comment by robinjia** [comment]
Hey guys,

Biggest comment: **MeSH is human-generated.**  That was the whole reason we're using it for distant supervision.  See http://www.ncbi.nlm.nih.gov/books/NBK3827/#pubmedhelp.MeSH_Terms_MH "Skilled subject analysts examine journal articles and assign to each the most specific MeSH terms applicable - typically ten to twelve. Applying the MeSH vocabulary ensures that articles are uniformly indexed by subject, whatever the author's words."

If you do want to keep this resource, you should probably just create a table in the database and dump the MeSH data there, then add it to the join in application.conf that feeds data to the extractor.

btw this is not the first time Chris A. has had lots of processes on raiders2 with 0 CPU usage but high memory usage...not sure what's up with that

**Comment by ajratner** [comment]
@robinjia He's back!!  :)  Perhaps they used some sort of human-guided annotation tool?  Either way db table works fine too.

Yeah for some reason on essentially all the raiders machines there are like billions of caberger zombie processes always haha...

**Comment by Colossus** [comment]
@robinjia Thanks for the input! That's good to know. Poor little humans, annotating 8 million articles.

@ajratner About caberger: Well, each of his processes is only using a few GB, but he has tons of these processes that use that much RAM. order htop by RAM, it's quite impressive.

BTW why "these are zombies, let's restart raiders"? How about he executes `killall -9 command_name`? Like `killall -9 python` or whatever he was running? Since he's not root, it's only going to kill his stuff.

**Comment by Colossus** [comment]
In any case, we can still use MeSH, only perhaps let's filter it by the PMIDs that we're actually using. I don't think we have anything close to 8 million in the current dataset, and even in the full dataset, is it ever going to grow to 8 million?

Even if it is, then we can only load those pubmed IDs that are being processed into the current batch. Since at most 100000 sentences are being loaded, this should get rid of all errors, past and future, that we ever had and will have.

EDIT: Or, in fact, listen to @robinjia and load the whole table into the database, which is probably the most reasonable thing.

**Comment by Colossus** [comment]
Final point. Regarding the 256GB limit. This does not seem to be enforced. In htop, you see that without us running anything, we're at like 54GB. (OK, whatever, I misplaced the decimal point in all my previous calculations.) But when we run our thing, RAM usage quickly pops out towards the whole TB, which is also the reason the OS is killing all of the user's (i.e., our) processes, which is also the reason our shell session crashes, because the shell is killed as well. At least that's my interpretation of the various phenomena.

**Comment by ajratner** [comment]
Closed with reboot of raiders2 / see #44...

Apparently raiders machines are configured to check virtual memory to see if _real_ memory is available, and so a bunch of `caberger`'s zombie processes were not taking up too much real memory, but were taking up a ton of virtual mem...
