### ISSUE TITLE
Make sure Title DOI matches actual DOI; don't take DOI of citing paper

### ISSUE THREAD

**Issue by Colossus** [ajratner/dd-genomics#58]

**Comment by Colossus** [comment]
Currently, we're parsing references as titles. If a title appears as a reference before the article, then the ID of the title will be the DOI of the citing article, not the original article. This messes up the MeSH Pheno supervision, which needs the correct DOI.

**Comment by gbgbg** [comment]
(Can also allow you to uniquify on DOI so as not to read the same title n times for all the papers that cite it?)

-Gill

**Comment by Colossus** [comment]
We already did that

**Comment by gbgbg** [comment]
best answer

**Comment by ajratner** [comment]
@gbgbg @Colossus indeed

We do string matching of titles + DOI check to ensure uniques, even then will not be perfect, will get a few duplicates probably, but doesn't matter too much / at all

**Comment by ajratner** [comment]
@Colossus Two points / questions:
1. So you are saying that there are _citing_ paper refs before the actual paper title?  Didn't know this occurred- good catch.  If so can we just capture them in the same way / with the same function as we do for "ref" sections?  What tag are they enclosed in?
2. **Should we then output the titles that come from refs with a docId corresponding to their DOI (not the DOI of the paper that they're within as references**?

**Comment by Colossus** [comment]
Yeah, this was exactly what I was trying to say

**Comment by ajratner** [comment]
I believe this is resolved in the current code- a ref tag will always trigger a call to `parseRef` which will 'consume' the citation DOI/pub-id, so the docId for the article should be correct.

One minor thing here: with my latest changes, the reference's `doc_id` will be its own pub-id, but it's `section_id` (the primary key) will be based on the citing article's id XXX (e.g. XXX.Ref.n).  Currently if this id (`docId`) is null the ref will be skipped.  I think for now, since I expect will lose so few refs this way, we should just leave this for consistency...
