### ISSUE TITLE
Check if gpfdist is running / autocheck?

### ISSUE THREAD

**Issue by ajratner** [ajratner/dd-genomics#63]

**Comment by ajratner** [comment]
@netj Pardon my ignorance / laziness here, but I don't think we've had `gpfdist` running for some of our recent deepdive runs.  I can / will soon get some actual evidence about this... but are there large performance gains from having it running vs. not?

**Comment by ajratner** [comment]
Also I tried running it (`gpfdist -d ${GPPATH} -p ${GPPORT} -m 268435456 &`) as I'd done before and it throws a `command not found` error...

**Comment by netj** [comment]
Make sure greenplum's bin is on your PATH:

``` bash
export PATH="/dfs/scratch1/netj/wrapped/greenplum:$PATH"
```

If you don't have `inference.parallel_grounding` or `db.default.gpload` turned on, gpfdist won't be used.  If either config is turned on, you need to keep it running.  Otherwise, weird errors will pop up.  This is another part DD could have been more user friendly.  We'll probably have DD launch gpfdist automatically when necessary, but for now you'll have to manage it.

**Comment by netj** [comment]
Inserting a few lines to your run.sh may do the job for now: https://github.com/HazyResearch/deepdive/blob/v0.6.x/test/test_gp.sh#L32-L35

**Comment by Colossus** [comment]
@ajratner We should change `PARALLEL_GROUNDING=false` to `PARALLEL_GROUNDING=true` in our `env_local.sh` to make sure we have parallelism using greemplum like @netj advised.

I also inserted @netj 's lines into `run.sh` for safety
